version: '3.7'
services:
  datetime_mensa:
    build: .
    container_name: datetime_mensa
    restart: always
    networks:
      - nginx
    volumes:
      - ./dist/speiseplan.xml:/usr/share/nginx/html/speiseplan.xml
networks:
  nginx:
    name: nginx

